version: '2.0'
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile.example.com:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev
      - TIME_ZONE=Europe/Moscow
      - SEAFILE_ADMIN_EMAIL=test@example.com
      - SEAFILE_ADMIN_PASSWORD=_Aa123456
      - SEAFILE_SERVER_LETSENCRYPT=false
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

  tests:
    build:
      context: ../
      dockerfile: ./aseafile_tests/Dockerfile
    command: sh aseafile_tests/wait_for_aseafile.sh  "python -m pytest"
    environment:
      - BASE_URL=http://seafile.example.com
      - EMAIL=test@example.com
      - PASSWORD=_Aa123456
    depends_on:
      - seafile.example.com
    networks:
      - seafile-net

networks:
  seafile-net: